name: Build/Release
on: [push, pull_request]

permissions:
  contents: write

env:
  NeosPath: "${{ github.workspace }}/neos_install/" #see neos-modding-group/neos-plugin-setup-action
  BUILD_TYPE: "CICD"
  UPLOAD_ARTIFACTS: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' }} # only publish workflow artifacts for pushes to main or tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: neos-modding-group/neos-plugin-setup-action@master
        #TODO: check for possible caching of neos build env
      - name: Download NeosModLoader and Harmony
        run: |
          mkdir -p "${NeosPath}/nml_libs" "${NeosPath}/Libraries"
          cd "${NeosPath}/nml_libs" && wget "https://github.com/neos-modding-group/NeosModLoader/releases/latest/download/0Harmony.dll"
          cd "${NeosPath}/Libraries" && wget "https://github.com/neos-modding-group/NeosModLoader/releases/latest/download/NeosModLoader.dll"
      - name: Lint
        run: dotnet format --verbosity detailed --verify-no-changes ./NeosDocumentImport.sln
      - name: Build binaries, create release directory structure, calculate sha256 checksums
        run: |
          dotnet build ./NeosDocumentImport.sln --configuration Release

          mkdir ./release
          mkdir ./release/nml_mods
          mkdir ./release/nml_libs
          
          mv ./NeosDocumentImport/bin/Release/net462/win-x64/NeosDocumentImport.dll ./release/nml_mods/NeosDocumentImport.dll
          
          mv ./NeosDocumentImport_PDFConverter/bin/Release/net462/win-x64/NeosDocumentImport_PDFConverter.dll ./release/nml_mods/NeosDocumentImport_PDFConverter.dll
          mv ./NeosDocumentImport_PDFConverter/bin/Release/net462/win-x64/pdfium.dll ./release/pdfium.dll
          mv ./NeosDocumentImport_PDFConverter/bin/Release/net462/win-x64/Docnet.Core.dll ./release/nml_libs/Docnet.Core.dll
          
          mv ./NeosDocumentImport_SVGConverter/bin/Release/net462/win-x64/NeosDocumentImport_SVGConverter.dll ./release/nml_mods/NeosDocumentImport_SVGConverter.dll
          mv ./NeosDocumentImport_SVGConverter/bin/Release/net462/win-x64/ExCSS.dll ./release/nml_libs/ExCSS.dll
          mv ./NeosDocumentImport_SVGConverter/bin/Release/net462/win-x64/Fizzler.dll ./release/nml_libs/Fizzler.dll
          mv ./NeosDocumentImport_SVGConverter/bin/Release/net462/win-x64/Svg.dll ./release/nml_libs/Svg.dll
          
          sha256sum ./release/*.dll ./release/*/*.dll
          
          echo "${UPLOAD_ARTIFACTS}"
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: 'zip'
          filename: 'NeosDocumentImport.zip'
          path: '.'
          directory: './release'
      - name: Upload artifacts
        if: ${{ env.UPLOAD_ARTIFACTS }}
        uses: actions/upload-artifact@v3
        with:
          name: NeosDocumentImport
          path: ./release/NeosDocumentImport.zip
          if-no-files-found: error
      - name: Create release draft
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/NeosDocumentImport.zip
          draft: true
